language: go
go:
  - release
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls
env:
  global:
    secure: oinDOcxfLucbpewKIEvjv53LmC0NOVMGwVHSlAxo2HjmQyHELawZUrR40fUMg3Dm3XvCuV+GjlkLLzukeqctdhzoUUuWjvStlV7OrpqB4Ir61Dqa/rcpagYD7IleyeXvXAXxsjUONlcd363z3E82WirFkbAs3dV451OQjghGGes=
